### ISSUE TITLE
Add group-prepend(append) for input

### ISSUE THREAD

**Issue by fey** [laraeast/laravel-bootstrap-forms#1]
https://getbootstrap.com/docs/4.1/components/input-group/
![image](https://user-images.githubusercontent.com/697178/95367850-b5c8b380-08ee-11eb-8d1b-c5914e1a0d67.png)

I think its should looks like
```
BsForm::prepend('string')->text()
Bsform::text()->append()
```
append\prepend can be called after and before input method

**Comment by ahmed-aliraqi** [comment]
Thanks for your suggestion,
I think the best would be to register a custom component for the input group in your own project.
It will look like:
```blade
{{ BsForm::textGroup('username')->prepend('@') }}
{{ BsForm::textGroup('email')->append('@example.com') }}
```
